image: golang:1.21

before_script:
    - git submodule update --init
pages:
    stage: deploy
    script:
    - go run -tags "prod" .
    artifacts:
        paths:
        - public
    only:
    - master
