image: python:3.7

pages:
    stage: deploy
    script:
    - cd post-to-html/ctypes-test
    - ./compile.sh
    - cd ../..
    - pip3 install markdown
    - python3 generate_website.py
    artifacts:
        paths:
        - public
    only:
    - master
