image: python:3.7

pages:
    stage: deploy
    script:
    - ./post-to-html/compile.sh
    - pip3 install markdown
    - python3 generate_website.py
    artifacts:
        paths:
        - public
    only:
    - master
